#!/usr/bin/env zsh
# shellcheck disable=SC1071
#
# Zimfw layer sourced after zsh/zshrc-base.
# Wired in by install_zimfw.sh via a marker block in $ZDOTDIR/.zshrc.
#

# Location of the zimfw framework script and its module cache
export ZIM_HOME=${XDG_CONFIG_HOME}/zim

##################################
# Pre-init module initialization #
##################################

#
# theme colors
#

# Branch color used by zim's git-info module
export BRANCH_COLOR=37

#
# input
#

# Append `../` to your input for each `.` you type after an initial `..`
zstyle ':zim:input' double-dot-expand yes

#
# git
#

# Set a custom prefix for the generated aliases. The default prefix is 'G'.
zstyle ':zim:git' aliases-prefix 'g'

#
# ssh
#

# Load these ssh identities with the ssh module
zstyle ':zim:ssh' ids 'id_rsa' 'id_ed25519'

#
# termtitle
#

# Set a custom terminal title format using prompt expansion escape sequences.
# See http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Simple-Prompt-Escapes
# If none is provided, the default '%n@%m: %~' is used.
#zstyle ':zim:termtitle' format '%1~'

#
# completion
#

# Move zim's completion dumpfile under XDG_CACHE_HOME (dir created by install_zsh).
# The ${ZSH_VERSION} suffix avoids stale-dump errors after a zsh upgrade.
zstyle ':zim:completion' dumpfile "${XDG_CACHE_HOME}/zsh/zcompdump-${ZSH_VERSION}"

# zsh's own completion cache (used by some completers)
zstyle ':completion::complete:*' cache-path "${XDG_CACHE_HOME}/zsh/zcompcache"

#
# zsh-autosuggestions
#

# Disable automatic widget re-binding on each precmd to boost performance.
# This can be set when zsh-users/zsh-autosuggestions is the last module in your ~/.zimrc.
ZSH_AUTOSUGGEST_MANUAL_REBIND=1

# Customize the style that the suggestions are shown with.
# See https://github.com/zsh-users/zsh-autosuggestions/blob/master/README.md#suggestion-highlight-style
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=23'

# Prevent suggestion of some huge paste buffer
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=80

#
# zsh-syntax-highlighting
#

# Set what highlighters will be used.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# Customize the main highlighter styles.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md#how-to-tweak-it
#typeset -A ZSH_HIGHLIGHT_STYLES
#ZSH_HIGHLIGHT_STYLES[comment]='fg=242'

############################
# Initialize zimfw modules #
############################

# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  source ${DOTFILES}/zimfw/install_zimfw.sh
  download_zimfw
fi
# Install missing modules, and update static ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZIM_CONFIG_FILE:-${ZDOTDIR:-${HOME}}/.zimrc} ]]; then
  source ${ZIM_HOME}/zimfw.zsh init
fi
# Initialize modules.
source ${ZIM_HOME}/init.zsh

###################################
# Post-init module initialization #
###################################

#
# zsh-history-substring-search module
#

# Bind ^[[A/^[[B manually so up/down works both before and after zle-line-init
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Bind up and down keys
zmodload -F zsh/terminfo +p:terminfo
if [[ -n ${terminfo[kcuu1]} && -n ${terminfo[kcud1]} ]]; then
 bindkey ${terminfo[kcuu1]} history-substring-search-up
 bindkey ${terminfo[kcud1]} history-substring-search-down
fi

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
# bindkey -M vicmd 'k' history-substring-search-up
# bindkey -M vicmd 'j' history-substring-search-down

#
# zsh-autosuggestions widgets
#

# Ctrl+o accept and execute suggestion
bindkey "^o" autosuggest-execute

# Alt+o accept suggestion without moving the cursor
function autosuggest-accept-in-place() {
  local cursor_pos=$CURSOR
  zle autosuggest-accept
  CURSOR=cursor_pos
}
zle -N autosuggest-accept-in-place
bindkey "^[o" autosuggest-accept-in-place

#
# git module
#

# Add or adjust git aliases (use anonymous function for scoping of variables)
() {
  local gprefix
  zstyle -s ':zim:git' aliases-prefix 'gprefix'

  # Git Index Add All
  alias ${gprefix}iaa='git add -A'
  # Git Branch All
  alias ${gprefix}ba="git branch -a"
  # Git Commit amend (or "force")
  alias ${gprefix}cf='git commit --verbose --amend'
  # Git Commit amend (or "force") reusing message
  alias ${gprefix}cF='git commit --amend --reuse-message HEAD'
  # Git Fetch All (and already prune deleted branches)
  alias ${gprefix}fa='git fetch --all --prune'
  # Git log graph (https://stackoverflow.com/a/9074343/4783169)
  alias ${gprefix}la="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) %C(white)%s%C(reset) %C(auto)%d%C(reset)%n''          %C(dim white) %an%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)%ar%C(reset)'"
  # Git local branches (no remote tracking yet)
  alias ${gprefix}loc="git branch -vv | cut -c 3- | awk '"'$3 !~ /\[origin/ { print $1 }'"'"
  # Git gone branches (gone remote tracking)
  alias ${gprefix}gone="git fetch --all --prune -q && git branch -vv | cut -c 3- | awk '"'/\[origin.*: gone\]/ { print $1 }'"'"
}
