#!/usr/bin/env zsh
# shellcheck disable=SC1071
#
# Initial setup file for both interactive and noninteractive zsh
#
# Read config sequence (except /etc/*)
#
#  login shell
#    $HOME/.zshenv -> stub includes $DOTFILES/zsh/zshenv-base
#    $ZDOTDIR/.zprofile
#    $ZDOTDIR/.zshrc
#    $ZDOTDIR/.zlogin
#
#  interactive zsh
#    $HOME/.zshenv
#    $ZDOTDIR/.zshrc
#
#  shell scripts
#    $HOME/.zshenv
#
#  remote noninteractive zsh (e.g. ssh hostname command)
#    $HOME/.zshenv
#
#  logout:
#    $ZDOTDIR/.zlogout
#    /etc/zlogout
#
# Thanks to: https://github.com/yonchu/dotfiles/blob/master/.zsh/.zshenv
#

# Define default XDG Base Directory Specification directories
(( ! ${+XDG_CONFIG_HOME} )) && export XDG_CONFIG_HOME=${HOME}/.config && mkdir -p $XDG_CONFIG_HOME
(( ! ${+XDG_CACHE_HOME} )) && export XDG_CACHE_HOME=${HOME}/.cache && mkdir -p $XDG_CACHE_HOME
(( ! ${+XDG_DATA_HOME} )) && export XDG_DATA_HOME=${HOME}/.local/share && mkdir -p $XDG_DATA_HOME

# Define DOTFILES repository path (set by .zshenv stub; default if sourced standalone)
: "${DOTFILES:=${HOME}/dotfiles}"
export DOTFILES

# Setup ZDOTDIR, the directory to search the other startup files (.zshrc, etc).
# Machine-local stubs live here; each one sources its repo counterpart.
export ZDOTDIR=${XDG_CONFIG_HOME}/zsh

# Define data path for asdf version manager
export ASDF_DATA_DIR=${XDG_DATA_HOME}/asdf
